### ISSUE TITLE
載入速度偏慢

### ISSUE THREAD

**Issue by sun92122** [sun92122/split_phy#1]
實際計時初始化、影音解碼到視窗顯示最多約 1.5 秒，但執行檔明顯需要 5 到 7 秒，推測可能是 pyinstaller 造成的效能低下，考慮包裝為資料夾而非檔案來加速。
reference: [App created with PyInstaller has a slow startup](https://stackoverflow.com/questions/9469932/app-created-with-pyinstaller-has-a-slow-startup)

**Comment by sun92122** [comment]
看來用單檔案的封裝方式會把大量 dll 檔暫存到 `_MEIxxxx` 資料夾內，Windows 的垃圾 IO 加上還要被防毒從旁邊桶才會那麼慢，看來似乎真的得封裝成資料夾才行。

**Comment by xup6rmp4jo3** [comment]
可以解釋一下什麼是dll檔嗎?
謝謝。我可以請你吃早餐。

**Comment by sun92122** [comment]
@snorlaxfatashell 
[自己看](https://zh.wikipedia.org/wiki/%E5%8A%A8%E6%80%81%E9%93%BE%E6%8E%A5%E5%BA%93?wprov=sfti1)

**Comment by xup6rmp4jo3** [comment]
好耶
